### PR TITLE
fix: ESM `import()` compatibility

### LINKED ISSUE #24: Allow plugin import using `import()`
Hi! First of all, thank you for such a cool plugin!

I tried to use it as described in README:

```js
// .prettierrc.js
module.exports = {
  plugins: ["prettier-plugin-pkgsort"]
}
```

But got the following error from prettier:
```
[error] No "exports" main defined in /.../node_modules/prettier-plugin-pkgsort/package.json imported from /home/auvred/shared-volume/prettier-sandbox/noop.js
```

Prettier imports plugins with `import()` expression and according to [this](https://nodejs.org/api/esm.html#resolution-algorithm), it respects only `default`, `node` and `import` conditions

---

Would it be possible to make change like this?

```diff
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
-     "require": "./dist/index.cjs"
+     "default": "./dist/index.cjs"
    },
    "./worker": {
      "require": "./dist/worker.cjs"
    }
```

I tested it locally and `pkgroll` works fine with this:

https://github.com/privatenumber/pkgroll/blob/ea9328217845d715330551daffbc5d2dced05c17/src/utils/parse-package-json/get-export-entries.ts#L93-L98

---

Also for some reason the published `dist` contains both `.mjs` and `.cjs` files. Not sure why, because when I build it locally, it outputs only `.cjs` files (I guess this might be resolved after re-publishing?)

image

### PR DESCRIPTION
**Pull request by auvred**
Fixes https://github.com/so1ve/prettier-plugin-pkgsort/issues/24

### CODE REVIEW

**Comment by so1ve** [comment]
Hi @auvred, thanks for your fix. 👍 

Does it make sense to add `import` field to `exports` too? `"import": "./dist/index.mjs"

And shall we add a `module` field to `package.json`? Currently this module is CJS-only, because I used to stick on Prettier 2.

I'm ok with your changes, just some suggestions.

**Comment by auvred** [comment]
`import()` can import cjs too, so we'll just duplicate similar code (I may be wrong). But it certainly will work with both `require` and `import`, so it's up to you :)

I am always in favor of migration to ESM! If this is possible, let's move to `"type": "module"`

**Comment by so1ve** [comment]
I'd love to use pure esm, however I can't move to it for some reason. Let's keep using cjs :)

~~But the tests seemed to fail on windows. Any thoughts?~~

Ah you have fixed them. Nice work!

**Review by so1ve — APPROVED** [review]
Thank you!

**Comment by so1ve** [comment]
Released https://github.com/so1ve/prettier-plugin-pkgsort/releases/tag/v0.2.1

**Comment by auvred** [comment]
Thanks! Can confirm that now it works

**Pull request merged**
